baseURL = 'https://nxy7.github.io/personal_blog'
languageCode = 'pl-PL'
title = 'just some developer thoughts'
theme = 'PaperMod'

disqusShortname = 'nxyt'
[params]
  comments = true
  name = 'Dawid Danieluk'
  bio = 'I like learning about new technologies that can make my work easier.'
